export const locations = [
  {
    id: "loc_1",
    name: "贺兰山苏峪口",
    tags: ["银河拱门", "光害低"],
    coverImage: "/images/landscape-milkyway-1.jpg",
    coordinates: "38.6° N, 106.0° E",
    elevation: "2,900m",
    bortle: 2,
    viirs: 0.8,
    status: "recommended",
    bestHour: "02:00",
    score: 92,
    distance: "150km",
    cloudCover: 10,
    precipitation: 0,
    moonPhase: "新月",
  },
  {
    id: "loc_2",
    name: "腾格里沙漠通湖草原",
    tags: ["地景丰富", "前景开阔"],
    coverImage: "/images/landscape-milkyway-4.jpg",
    coordinates: "37.6° N, 105.0° E",
    elevation: "1,300m",
    bortle: 1,
    viirs: 0.2,
    status: "recommended",
    bestHour: "01:00",
    score: 95,
    distance: "210km",
    cloudCover: 5,
    precipitation: 0,
    moonPhase: "新月",
  },
  {
    id: "loc_3",
    name: "中卫沙坡头",
    tags: ["便利", "光害中"],
    coverImage: "/images/landscape-milkyway-2.jpg",
    coordinates: "37.5° N, 105.0° E",
    elevation: "1,200m",
    bortle: 4,
    viirs: 3.5,
    status: "watch",
    bestHour: "23:00",
    score: 78,
    distance: "180km",
    cloudCover: 45,
    precipitation: 20,
    moonPhase: "残月",
  },
  {
    id: "loc_4",
    name: "六盘山",
    tags: ["高海拔", "路途远"],
    coverImage: "/images/landscape-milkyway-5.jpg",
    coordinates: "35.7° N, 106.2° E",
    elevation: "2,800m",
    bortle: 2,
    viirs: 1.0,
    status: "watch",
    bestHour: "03:00",
    score: 85,
    distance: "320km",
    cloudCover: 30,
    precipitation: 10,
    moonPhase: "新月",
  },
  {
    id: "loc_5",
    name: "银川市区",
    tags: ["测试点", "光害高"],
    coverImage: "/images/landscape-milkyway-3.jpg",
    coordinates: "38.5° N, 106.3° E",
    elevation: "1,100m",
    bortle: 7,
    viirs: 25.0,
    status: "not_recommended",
    bestHour: "N/A",
    score: 20,
    distance: "10km",
    cloudCover: 60,
    precipitation: 40,
    moonPhase: "新月",
  },
];

export const hourlyData = Array.from({ length: 24 }, (_, i) => ({
  hour: `${String(i).padStart(2, "0")}:00`,
  cloudCover: Math.floor(Math.random() * 100),
  precipitation: Math.floor(Math.random() * 50),
  moonAlt: Math.random() * 90 - 30,
  milkyWayVisible: i >= 22 || i <= 4,
}));
